modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="evenbetternether"
version="1.2.0"
displayName="Even Better Nether"
displayURL="https://ko-fi.com/autumnly"
logoFile="logo.png"
credits="Created by Autumnly24, inspired by Better Nether"
authors="Autumn"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.evenbetternether]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.evenbetternether]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration