modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="evenbetternether"
version="1.1.0"
displayName="Even Better Nether"
displayURL="https://ko-fi.com/autumnly"
logoFile="logo.png"
credits="Created by Autumnly24, inspired by Better Nether"
authors="Autumn"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.evenbetternether]]
modId="neoforge"
type="required"
versionRange="[21.1.65,)"
ordering="AFTER"
side="BOTH"

[[dependencies.evenbetternether]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"


[[dependencies.evenbetternether]]
modId="jei"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration