
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.evenbetternether.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.evenbetternether.block.WitheredNyliumBlock;
import net.mcreator.evenbetternether.block.WitherBoneGrowthsBlock;
import net.mcreator.evenbetternether.block.VerdantSproutsBlock;
import net.mcreator.evenbetternether.block.VerdantRootsBlock;
import net.mcreator.evenbetternether.block.VerdantNyliumBlock;
import net.mcreator.evenbetternether.block.TallNethershroomBlock;
import net.mcreator.evenbetternether.block.StrippedMushroomWoodBlock;
import net.mcreator.evenbetternether.block.StrippedMushroomLogBlock;
import net.mcreator.evenbetternether.block.StoneSpeleothemBlock;
import net.mcreator.evenbetternether.block.SoulSproutsBlock;
import net.mcreator.evenbetternether.block.SoulRootsBlock;
import net.mcreator.evenbetternether.block.SmoothBoneWallBlock;
import net.mcreator.evenbetternether.block.SmoothBoneStairsBlock;
import net.mcreator.evenbetternether.block.SmoothBoneSlabBlock;
import net.mcreator.evenbetternether.block.SmoothBoneBlockBlock;
import net.mcreator.evenbetternether.block.PyriteWallBlock;
import net.mcreator.evenbetternether.block.PyriteTilesBlock;
import net.mcreator.evenbetternether.block.PyriteTileStairsBlock;
import net.mcreator.evenbetternether.block.PyriteTileSlabBlock;
import net.mcreator.evenbetternether.block.PyriteStairsBlock;
import net.mcreator.evenbetternether.block.PyriteSlabBlock;
import net.mcreator.evenbetternether.block.PyriteRoofingStairsBlock;
import net.mcreator.evenbetternether.block.PyriteRoofingSlabBlock;
import net.mcreator.evenbetternether.block.PyriteRoofingBlock;
import net.mcreator.evenbetternether.block.PyriteLampBlock;
import net.mcreator.evenbetternether.block.PyriteBricksBlock;
import net.mcreator.evenbetternether.block.PyriteBrickStairsBlock;
import net.mcreator.evenbetternether.block.PyriteBrickSlabBlock;
import net.mcreator.evenbetternether.block.PyriteBrickPillarBlock;
import net.mcreator.evenbetternether.block.PyriteBlockBlock;
import net.mcreator.evenbetternether.block.NyceliumBlock;
import net.mcreator.evenbetternether.block.NethershroomBlock;
import net.mcreator.evenbetternether.block.NetherrackSpeleothemBlock;
import net.mcreator.evenbetternether.block.NetherSaguaroBlock;
import net.mcreator.evenbetternether.block.NetherRubyOreBlock;
import net.mcreator.evenbetternether.block.NetherRubyBlockBlock;
import net.mcreator.evenbetternether.block.NetherPyriteOreBlock;
import net.mcreator.evenbetternether.block.NetherMushroomCapBlock;
import net.mcreator.evenbetternether.block.NetherAgaveBlock;
import net.mcreator.evenbetternether.block.MushroomWoodBlock;
import net.mcreator.evenbetternether.block.MushroomTrapdoorBlock;
import net.mcreator.evenbetternether.block.MushroomStairsBlock;
import net.mcreator.evenbetternether.block.MushroomSlabBlock;
import net.mcreator.evenbetternether.block.MushroomPressurePlateBlock;
import net.mcreator.evenbetternether.block.MushroomPlanksBlock;
import net.mcreator.evenbetternether.block.MushroomLogBlock;
import net.mcreator.evenbetternether.block.MushroomFenceGateBlock;
import net.mcreator.evenbetternether.block.MushroomFenceBlock;
import net.mcreator.evenbetternether.block.MushroomDoorBlock;
import net.mcreator.evenbetternether.block.MushroomButtonBlock;
import net.mcreator.evenbetternether.block.LongHangingMyceliumBlock;
import net.mcreator.evenbetternether.block.LigniteOreBlock;
import net.mcreator.evenbetternether.block.HangingMyceliumBlock;
import net.mcreator.evenbetternether.block.GlowstoneSpeleothemBlock;
import net.mcreator.evenbetternether.block.FungalSproutsBlock;
import net.mcreator.evenbetternether.block.FungalRootsBlock;
import net.mcreator.evenbetternether.block.FeatherFernBlock;
import net.mcreator.evenbetternether.block.DeepslateSpeleothemBlock;
import net.mcreator.evenbetternether.block.ChiseledPyriteBlock;
import net.mcreator.evenbetternether.block.CharredSproutsBlock;
import net.mcreator.evenbetternether.block.CarvedPyriteWallBlock;
import net.mcreator.evenbetternether.block.CarvedPyriteStairsBlock;
import net.mcreator.evenbetternether.block.CarvedPyriteSlabBlock;
import net.mcreator.evenbetternether.block.CarvedPyriteBlock;
import net.mcreator.evenbetternether.block.BurningSproutsBlock;
import net.mcreator.evenbetternether.block.BurningRootsBlock;
import net.mcreator.evenbetternether.block.BulbousHangingMyceliumBlock;
import net.mcreator.evenbetternether.block.BrownNetherMushroomCapBlock;
import net.mcreator.evenbetternether.block.BoneSpeleothemBlock;
import net.mcreator.evenbetternether.block.BoneGrowthsBlock;
import net.mcreator.evenbetternether.block.BlackstoneSpeleothemBlock;
import net.mcreator.evenbetternether.block.BasaltSpeleothemBlock;
import net.mcreator.evenbetternether.block.BarrelCactusBlock;
import net.mcreator.evenbetternether.EvenbetternetherMod;

public class EvenbetternetherModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, EvenbetternetherMod.MODID);
	public static final RegistryObject<Block> VERDANT_NYLIUM = REGISTRY.register("verdant_nylium", () -> new VerdantNyliumBlock());
	public static final RegistryObject<Block> VERDANT_ROOTS = REGISTRY.register("verdant_roots", () -> new VerdantRootsBlock());
	public static final RegistryObject<Block> BONE_GROWTHS = REGISTRY.register("bone_growths", () -> new BoneGrowthsBlock());
	public static final RegistryObject<Block> FEATHER_FERN = REGISTRY.register("feather_fern", () -> new FeatherFernBlock());
	public static final RegistryObject<Block> SMOOTH_BONE_BLOCK = REGISTRY.register("smooth_bone_block", () -> new SmoothBoneBlockBlock());
	public static final RegistryObject<Block> SMOOTH_BONE_STAIRS = REGISTRY.register("smooth_bone_stairs", () -> new SmoothBoneStairsBlock());
	public static final RegistryObject<Block> SMOOTH_BONE_SLAB = REGISTRY.register("smooth_bone_slab", () -> new SmoothBoneSlabBlock());
	public static final RegistryObject<Block> SMOOTH_BONE_WALL = REGISTRY.register("smooth_bone_wall", () -> new SmoothBoneWallBlock());
	public static final RegistryObject<Block> NETHER_AGAVE = REGISTRY.register("nether_agave", () -> new NetherAgaveBlock());
	public static final RegistryObject<Block> VERDANT_SPROUTS = REGISTRY.register("verdant_sprouts", () -> new VerdantSproutsBlock());
	public static final RegistryObject<Block> NETHER_SAGUARO = REGISTRY.register("nether_saguaro", () -> new NetherSaguaroBlock());
	public static final RegistryObject<Block> BARREL_CACTUS = REGISTRY.register("barrel_cactus", () -> new BarrelCactusBlock());
	public static final RegistryObject<Block> SOUL_ROOTS = REGISTRY.register("soul_roots", () -> new SoulRootsBlock());
	public static final RegistryObject<Block> SOUL_SPROUTS = REGISTRY.register("soul_sprouts", () -> new SoulSproutsBlock());
	public static final RegistryObject<Block> BASALT_SPELEOTHEM = REGISTRY.register("basalt_speleothem", () -> new BasaltSpeleothemBlock());
	public static final RegistryObject<Block> NETHERRACK_SPELEOTHEM = REGISTRY.register("netherrack_speleothem", () -> new NetherrackSpeleothemBlock());
	public static final RegistryObject<Block> BLACKSTONE_SPELEOTHEM = REGISTRY.register("blackstone_speleothem", () -> new BlackstoneSpeleothemBlock());
	public static final RegistryObject<Block> GLOWSTONE_SPELEOTHEM = REGISTRY.register("glowstone_speleothem", () -> new GlowstoneSpeleothemBlock());
	public static final RegistryObject<Block> STONE_SPELEOTHEM = REGISTRY.register("stone_speleothem", () -> new StoneSpeleothemBlock());
	public static final RegistryObject<Block> DEEPSLATE_SPELEOTHEM = REGISTRY.register("deepslate_speleothem", () -> new DeepslateSpeleothemBlock());
	public static final RegistryObject<Block> BONE_SPELEOTHEM = REGISTRY.register("bone_speleothem", () -> new BoneSpeleothemBlock());
	public static final RegistryObject<Block> NYCELIUM = REGISTRY.register("nycelium", () -> new NyceliumBlock());
	public static final RegistryObject<Block> WITHERED_NYLIUM = REGISTRY.register("withered_nylium", () -> new WitheredNyliumBlock());
	public static final RegistryObject<Block> BURNING_ROOTS = REGISTRY.register("burning_roots", () -> new BurningRootsBlock());
	public static final RegistryObject<Block> BURNING_SPROUTS = REGISTRY.register("burning_sprouts", () -> new BurningSproutsBlock());
	public static final RegistryObject<Block> CHARRED_SPROUTS = REGISTRY.register("charred_sprouts", () -> new CharredSproutsBlock());
	public static final RegistryObject<Block> WITHER_BONE_GROWTHS = REGISTRY.register("wither_bone_growths", () -> new WitherBoneGrowthsBlock());
	public static final RegistryObject<Block> NETHER_PYRITE_ORE = REGISTRY.register("nether_pyrite_ore", () -> new NetherPyriteOreBlock());
	public static final RegistryObject<Block> PYRITE_BLOCK = REGISTRY.register("pyrite_block", () -> new PyriteBlockBlock());
	public static final RegistryObject<Block> LIGNITE_ORE = REGISTRY.register("lignite_ore", () -> new LigniteOreBlock());
	public static final RegistryObject<Block> NETHER_RUBY_ORE = REGISTRY.register("nether_ruby_ore", () -> new NetherRubyOreBlock());
	public static final RegistryObject<Block> NETHER_RUBY_BLOCK = REGISTRY.register("nether_ruby_block", () -> new NetherRubyBlockBlock());
	public static final RegistryObject<Block> MUSHROOM_WOOD = REGISTRY.register("mushroom_wood", () -> new MushroomWoodBlock());
	public static final RegistryObject<Block> MUSHROOM_LOG = REGISTRY.register("mushroom_log", () -> new MushroomLogBlock());
	public static final RegistryObject<Block> MUSHROOM_PLANKS = REGISTRY.register("mushroom_planks", () -> new MushroomPlanksBlock());
	public static final RegistryObject<Block> MUSHROOM_STAIRS = REGISTRY.register("mushroom_stairs", () -> new MushroomStairsBlock());
	public static final RegistryObject<Block> MUSHROOM_SLAB = REGISTRY.register("mushroom_slab", () -> new MushroomSlabBlock());
	public static final RegistryObject<Block> MUSHROOM_FENCE = REGISTRY.register("mushroom_fence", () -> new MushroomFenceBlock());
	public static final RegistryObject<Block> MUSHROOM_FENCE_GATE = REGISTRY.register("mushroom_fence_gate", () -> new MushroomFenceGateBlock());
	public static final RegistryObject<Block> MUSHROOM_PRESSURE_PLATE = REGISTRY.register("mushroom_pressure_plate", () -> new MushroomPressurePlateBlock());
	public static final RegistryObject<Block> MUSHROOM_BUTTON = REGISTRY.register("mushroom_button", () -> new MushroomButtonBlock());
	public static final RegistryObject<Block> MUSHROOM_DOOR = REGISTRY.register("mushroom_door", () -> new MushroomDoorBlock());
	public static final RegistryObject<Block> MUSHROOM_TRAPDOOR = REGISTRY.register("mushroom_trapdoor", () -> new MushroomTrapdoorBlock());
	public static final RegistryObject<Block> STRIPPED_MUSHROOM_LOG = REGISTRY.register("stripped_mushroom_log", () -> new StrippedMushroomLogBlock());
	public static final RegistryObject<Block> STRIPPED_MUSHROOM_WOOD = REGISTRY.register("stripped_mushroom_wood", () -> new StrippedMushroomWoodBlock());
	public static final RegistryObject<Block> NETHER_MUSHROOM_CAP = REGISTRY.register("nether_mushroom_cap", () -> new NetherMushroomCapBlock());
	public static final RegistryObject<Block> BROWN_NETHER_MUSHROOM_CAP = REGISTRY.register("brown_nether_mushroom_cap", () -> new BrownNetherMushroomCapBlock());
	public static final RegistryObject<Block> TALL_NETHERSHROOM = REGISTRY.register("tall_nethershroom", () -> new TallNethershroomBlock());
	public static final RegistryObject<Block> NETHERSHROOM = REGISTRY.register("nethershroom", () -> new NethershroomBlock());
	public static final RegistryObject<Block> FUNGAL_ROOTS = REGISTRY.register("fungal_roots", () -> new FungalRootsBlock());
	public static final RegistryObject<Block> FUNGAL_SPROUTS = REGISTRY.register("fungal_sprouts", () -> new FungalSproutsBlock());
	public static final RegistryObject<Block> HANGING_MYCELIUM = REGISTRY.register("hanging_mycelium", () -> new HangingMyceliumBlock());
	public static final RegistryObject<Block> LONG_HANGING_MYCELIUM = REGISTRY.register("long_hanging_mycelium", () -> new LongHangingMyceliumBlock());
	public static final RegistryObject<Block> BULBOUS_HANGING_MYCELIUM = REGISTRY.register("bulbous_hanging_mycelium", () -> new BulbousHangingMyceliumBlock());
	public static final RegistryObject<Block> PYRITE_SLAB = REGISTRY.register("pyrite_slab", () -> new PyriteSlabBlock());
	public static final RegistryObject<Block> PYRITE_STAIRS = REGISTRY.register("pyrite_stairs", () -> new PyriteStairsBlock());
	public static final RegistryObject<Block> PYRITE_TILES = REGISTRY.register("pyrite_tiles", () -> new PyriteTilesBlock());
	public static final RegistryObject<Block> PYRITE_TILE_STAIRS = REGISTRY.register("pyrite_tile_stairs", () -> new PyriteTileStairsBlock());
	public static final RegistryObject<Block> PYRITE_TILE_SLAB = REGISTRY.register("pyrite_tile_slab", () -> new PyriteTileSlabBlock());
	public static final RegistryObject<Block> PYRITE_WALL = REGISTRY.register("pyrite_wall", () -> new PyriteWallBlock());
	public static final RegistryObject<Block> PYRITE_ROOFING = REGISTRY.register("pyrite_roofing", () -> new PyriteRoofingBlock());
	public static final RegistryObject<Block> PYRITE_ROOFING_STAIRS = REGISTRY.register("pyrite_roofing_stairs", () -> new PyriteRoofingStairsBlock());
	public static final RegistryObject<Block> PYRITE_ROOFING_SLAB = REGISTRY.register("pyrite_roofing_slab", () -> new PyriteRoofingSlabBlock());
	public static final RegistryObject<Block> CARVED_PYRITE = REGISTRY.register("carved_pyrite", () -> new CarvedPyriteBlock());
	public static final RegistryObject<Block> CARVED_PYRITE_STAIRS = REGISTRY.register("carved_pyrite_stairs", () -> new CarvedPyriteStairsBlock());
	public static final RegistryObject<Block> CARVED_PYRITE_SLAB = REGISTRY.register("carved_pyrite_slab", () -> new CarvedPyriteSlabBlock());
	public static final RegistryObject<Block> CARVED_PYRITE_WALL = REGISTRY.register("carved_pyrite_wall", () -> new CarvedPyriteWallBlock());
	public static final RegistryObject<Block> CHISELED_PYRITE = REGISTRY.register("chiseled_pyrite", () -> new ChiseledPyriteBlock());
	public static final RegistryObject<Block> PYRITE_LAMP = REGISTRY.register("pyrite_lamp", () -> new PyriteLampBlock());
	public static final RegistryObject<Block> PYRITE_BRICKS = REGISTRY.register("pyrite_bricks", () -> new PyriteBricksBlock());
	public static final RegistryObject<Block> PYRITE_BRICK_STAIRS = REGISTRY.register("pyrite_brick_stairs", () -> new PyriteBrickStairsBlock());
	public static final RegistryObject<Block> PYRITE_BRICK_SLAB = REGISTRY.register("pyrite_brick_slab", () -> new PyriteBrickSlabBlock());
	public static final RegistryObject<Block> PYRITE_BRICK_PILLAR = REGISTRY.register("pyrite_brick_pillar", () -> new PyriteBrickPillarBlock());
	// Start of user code block custom blocks
	// End of user code block custom blocks
}
